apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: atlantis-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: atlantis-secret
  data:
    - secretKey: id_rsa
      remoteRef:
        key: atlantis-ssh-key

